<?php

namespace App\DTOs;

/**
 * Data Transfer Object for Strategy Signals
 *
 * Contains all information about a trading signal generated by a strategy
 */
class StrategySignalDTO
{
    public function __construct(
        public readonly string $strategyName,
        public readonly string $symbol,
        public readonly string $signal, // 'BUY', 'SELL', 'HOLD', 'CLOSE'
        public readonly float $strength, // 0-100, how strong is the signal
        public readonly float $confidence, // 0-100, confidence in the signal
        public readonly array $reasons, // Array of reasons for this signal
        public readonly array $indicators, // Indicator values used
        public readonly ?float $entryPrice = null,
        public readonly ?float $stopLoss = null,
        public readonly ?float $takeProfit = null,
        public readonly ?int $recommendedLeverage = null,
        public readonly ?float $positionSize = null,
        public readonly ?float $riskRewardRatio = null,
        public readonly array $metadata = [],
    ) {}

    public function toArray(): array
    {
        return [
            'strategy_name' => $this->strategyName,
            'symbol' => $this->symbol,
            'signal' => $this->signal,
            'strength' => $this->strength,
            'confidence' => $this->confidence,
            'reasons' => $this->reasons,
            'indicators' => $this->indicators,
            'entry_price' => $this->entryPrice,
            'stop_loss' => $this->stopLoss,
            'take_profit' => $this->takeProfit,
            'recommended_leverage' => $this->recommendedLeverage,
            'position_size' => $this->positionSize,
            'risk_reward_ratio' => $this->riskRewardRatio,
            'metadata' => $this->metadata,
        ];
    }

    public function shouldExecute(float $minStrength = 60, float $minConfidence = 70): bool
    {
        return $this->strength >= $minStrength
            && $this->confidence >= $minConfidence
            && in_array($this->signal, ['BUY', 'SELL', 'CLOSE']);
    }

    public function isValid(): bool
    {
        if ($this->signal === 'HOLD') {
            return true;
        }

        return $this->entryPrice !== null
            && $this->stopLoss !== null
            && $this->takeProfit !== null
            && $this->riskRewardRatio !== null
            && $this->riskRewardRatio >= 1.5;
    }
}
